feat: save all file
Signed-off-by: Xinwei Xiong(cubxxw-openim) <3293172751nss@gmail.com>

diff --git a/scripts/install/openim-crontask b/scripts/install/openim-crontask
--- a/scripts/install/openim-crontask
+++ b/scripts/install/openim-crontask
@@ -21,99 +21,83 @@ set -o pipefail
 OPENIM_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")"/../.. && pwd -P)
 [[ -z ${COMMON_SOURCED} ]] && source ${OPENIM_ROOT}/scripts/install/common.sh
 
-readonly SERVER_NAME="openim-crontask"
-readonly SERVER_PATH="${OPENIM_OUTPUT_HOSTBIN}/openim-crontask"
+SERVER_NAME="openim-crontask"
 
 openim::log::status "Start OpenIM Cron, binary root: ${SERVER_NAME}"
-openim::log::info "Start OpenIM Cron, path: ${SERVER_PATH}"
+openim::log::info "Start OpenIM Cron, path: ${OPENIM_CRONTASK_BINARY}"
 
-openim::util::stop_services_with_name ${SERVER_NAME}
+# openim::util::stop_services_with_name ${SERVER_NAME}
 
-sleep 1
+# sleep 1
 
-openim::log::status "start cron_task process"
+# openim::log::status "start cron_task process, path: ${OPENIM_CRONTASK_BINARY}"
+# nohup ${OPENIM_CRONTASK_BINARY} >>${LOG_FILE} 2>&1 &
+# openim::util::check_process_names ${SERVER_NAME}
 
-nohup ${SERVER_PATH} >>${log_file} 2>&1 &
+# # Print the necessary information after installation
+# function openim::crontask::info() {
+# cat << EOF
+# openim-crontask listen on: ${OPENIM_CRONTASK_HOST}
+# EOF
+# }
 
-# Check launched service process
-check=`ps  | grep -w ./${cron_task_name} | grep -v grep| wc -l`
-if [ $check -ge 1 ]
-then
-newPid=`ps  | grep -w ./${cron_task_name} | grep -v grep|awk '{print $2}'`
-allPorts=""
-    echo -e ${SKY_BLUE_PREFIX}"SERVICE START SUCCESS "${COLOR_SUFFIX}
-    echo -e ${SKY_BLUE_PREFIX}"SERVICE_NAME: "${COLOR_SUFFIX}${BACKGROUND_GREEN}${cron_task_name}${COLOR_SUFFIX}
-    echo -e ${SKY_BLUE_PREFIX}"PID: "${COLOR_SUFFIX}${BACKGROUND_GREEN}${newPid}${COLOR_SUFFIX}
-    echo -e ${SKY_BLUE_PREFIX}"LISTENING_PORT: "${COLOR_SUFFIX}${BACKGROUND_GREEN}${allPorts}${COLOR_SUFFIX}
-else
-    echo -e ${BACKGROUND_GREEN}${cron_task_name}${COLOR_SUFFIX}${RED_PREFIX}"\n SERVICE START ERROR, PLEASE CHECK openIM.log"${COLOR_SUFFIX}
-fi
-
-
-# Print the necessary information after installation
-function iam::pump::info() {
-cat << EOF
-iam-pumpn listen on: ${IAM_PUMP_HOST}
-EOF
-}
-
-# 安装
-function iam::pump::install()
+# install openim-crontask
+function openim::crontask::install()
 {
-  pushd ${IAM_ROOT}
+  pushd ${OPENIM_ROOT}
 
-  # 1. 构建 iam-pump
-  make build BINS=iam-pump
-  iam::common::sudo "cp ${LOCAL_OUTPUT_ROOT}/platforms/linux/amd64/iam-pump ${IAM_INSTALL_DIR}/bin"
+  # 1. Build openim-crontask
+  make build BINS=${SERVER_NAME}
+  openim::common::sudo "cp ${OPENIM_OUTPUT_HOSTBIN}/${SERVER_NAME} ${OPENIM_INSTALL_DIR}/bin"
 
-  # 2.  生成并安装 iam-pump 的配置文件（iam-pump.yaml）
+  # 2. Generate and install the openim-crontask configuration file (openim-crontask.yaml)
   echo ${LINUX_PASSWORD} | sudo -S bash -c \
-    "./scripts/genconfig.sh ${ENV_FILE} configs/iam-pump.yaml > ${IAM_CONFIG_DIR}/iam-pump.yaml"
+    "./scripts/genconfig.sh ${ENV_FILE} deployments/templates/openim-crontask.yaml > ${OPENIM_CONFIG_DIR}/openim-crontask.yaml"
 
-  # 3. 创建并安装 iam-pump systemd unit 文件
+  # 3. Create and install the openim-crontask systemd unit file
   echo ${LINUX_PASSWORD} | sudo -S bash -c \
-    "./scripts/genconfig.sh ${ENV_FILE} init/iam-pump.service > /etc/systemd/system/iam-pump.service"
+    "./scripts/genconfig.sh ${ENV_FILE} deployments/templates/init/openim-crontask.service > /etc/systemd/system/openim-crontask.service"
 
-  # 4. 启动 iam-pump 服务
-  iam::common::sudo "systemctl daemon-reload"
-  iam::common::sudo "systemctl restart iam-pump"
-  iam::common::sudo "systemctl enable iam-pump"
-  iam::pump::status || return 1
-  iam::pump::info
+  # 4. Start the openim-crontask service
+  openim::common::sudo "systemctl daemon-reload"
+  openim::common::sudo "systemctl restart openim-crontask"
+  openim::common::sudo "systemctl enable openim-crontask"
+  openim::crontask::status || return 1
+  openim::crontask::info
 
-  iam::log::info "install iam-pump successfully"
+  openim::log::info "install openim-crontask successfully"
   popd
 }
 
-# 卸载
-function iam::pump::uninstall()
+# Unload
+function openim::crontask::uninstall()
 {
   set +o errexit
-  iam::common::sudo "systemctl stop iam-pump"
-  iam::common::sudo "systemctl disable iam-pump"
-  iam::common::sudo "rm -f ${IAM_INSTALL_DIR}/bin/iam-pump"
-  iam::common::sudo "rm -f ${IAM_CONFIG_DIR}/iam-pump.yaml"
-  iam::common::sudo "rm -f /etc/systemd/system/iam-pump.service"
+  openim::common::sudo "systemctl stop openim-crontask"
+  openim::common::sudo "systemctl disable openim-crontask"
+  openim::common::sudo "rm -f ${OPENIM_INSTALL_DIR}/bin/openim-crontask"
+  openim::common::sudo "rm -f ${OPENIM_CONFIG_DIR}/openim-crontask.yaml"
+  openim::common::sudo "rm -f /etc/systemd/system/openim-crontask.service"
   set -o errexit
-  iam::log::info "uninstall iam-pump successfully"
+  openim::log::info "uninstall openim-crontask successfully"
 }
 
-# 状态检查
-function iam::pump::status()
+# Status Check
+function openim::crontask::status()
 {
-  # 查看 iam-pump 运行状态，如果输出中包含 active (running) 字样说明 iam-pump 成功启动。
-  systemctl status iam-pump|grep -q 'active' || {
-    iam::log::error "iam-pump failed to start, maybe not installed properly"
+  # 查看 openim-crontask 运行状态，如果输出中包含 active (running) 字样说明 openim-crontask 成功启动。
+  systemctl status openim-crontask|grep -q 'active' || {
+    openim::log::error "openim-crontask failed to start, maybe not installed properly"
     return 1
   }
 
   # 监听端口在配置文件中是 hardcode
   if echo | telnet 127.0.0.1 7070 2>&1|grep refused &>/dev/null;then
-    iam::log::error "cannot access health check port, iam-pump maybe not startup"
+    openim::log::error "cannot access health check port, openim-crontask maybe not startup"
     return 1
   fi
 }
 
-if [[ "$*" =~ iam::pump:: ]];then
+if [[ "$*" =~ openim::crontask:: ]];then
   eval $*
 fi
